### ISSUE TITLE
Getting Invalid path alias error since uninstalling

### ISSUE THREAD

**Issue by peteeveleigh** [nystudio107/craft-webperf#56]
### Question
Hey there

We are getting an error showing in the logs of a site where Webperf was installed but has since been removed.
Looks like it's possibly related to some compiled JS that is hanging around, but we can't find any trace of it anywhere on the site.

The error message is

`yii\base\InvalidArgumentException: Invalid path alias: @nystudio107/webperf/assetbundles/boomerang/dist/js in /home/forge/www.domain.com/vendor/yiisoft/yii2/BaseYii.php:154 Stack trace: #0 /home/forge/www.domain.com/vendor/craftcms/cms/src/web/Application.php(530): yii\BaseYii::getAlias() #1 /home/forge/www.domain.com/vendor/craftcms/cms/src/web/Application.php(163): craft\web\Application->_processResourceRequest() #2 /home/forge/www.domain.com/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest() #3 /home/forge/www.domain.com/web/index.php(21): yii\base\Application->run() #4 {main}`

Have tried clearing caches, reinstalling and uninstalling, rebuilding the site assets etc. All with no luck.

Have you any idea where this might be coming from and how we can eliminate it?

**Comment by khalwat** [comment]
If you look in your `vendor/nystudio107/` directory, do you see `craft-webperf` at all?

**Comment by peteeveleigh** [comment]
Nope. 
![Screenshot 2024-09-17 at 17 45 27](https://github.com/user-attachments/assets/07a3a4db-bf27-4609-ac4e-5f8f2efb01ff)

Likewise, if I search the entire project for the string 'webperf' or 'boomerang' there is nothing.

**Comment by khalwat** [comment]
I'm guessing this is cached somewhere -- maybe clear your Craft Template Caches?

**Comment by peteeveleigh** [comment]
Already tried clearing every cache I can find.

I'm wondering if something got compiled with Weperf installed but since then something has prevented it recompiling.

Will also check something isn't being cached on Cloudflare

**Comment by khalwat** [comment]
Yep certainly could be something cached in CloudFlare as well.
